version: 2.1

jobs:
  test-xmhf:
    machine:
      # Need nested virtualization
      # https://discuss.circleci.com/t/new-android-machine-image-now-/39467
      image: android:2022.03.1
    parameters:
      subarch:
        type: string
    steps:
      - checkout
      - run:
          name: "Apt-get"
          command: "
            sudo apt-get update && \
            sudo apt-get -y -q install \
                git crossbuild-essential-i386 \
                pbuilder texinfo ruby build-essential autoconf libtool \
                qemu-system-x86 sshpass
          "
      - run:
          name: "Build"
          command: "./.github/build.sh << parameters.subarch >>"
      - run:
          name: "Versions"
          command: |
            lscpu
            ssh -V
            qemu-system-x86_64 -version
            gcc -v
      - restore_cache:
          keys:
            - debian11x86x64-20220407-<< parameters.subarch >>
      - run:
          name: "Download Debian"
          command: |
            source .circleci/env.sh << parameters.subarch >>
            .jenkins/download.sh cache ${qemu_image_back}
      - save_cache:
          key: debian11x86x64-20220407-<< parameters.subarch >>
          paths:
            - cache/
      - run:
          name: "Test"
          command: |
            source .circleci/env.sh << parameters.subarch >>
            rm -rf tmp qemu
            mkdir tmp qemu
            ln -s ${PWD}/cache/${qemu_image_back} qemu
            qemu-img create -f qcow2 -b ${PWD}/qemu/${qemu_image_back} \
                            -F qcow2 ${PWD}/qemu/${qemu_image}
            sha512sum ${PWD}/qemu/${qemu_image_back}
            python3 -u ./.jenkins/test2.py \
                --subarch ${SUBARCH} \
                --qemu-image ${PWD}/qemu/${qemu_image} \
                --qemu-image-back ${PWD}/qemu/${qemu_image_back} \
                --xmhf-bin ${PWD}/ \
                --sshpass jkl \
                --work-dir ${PWD}/tmp/ \
                --no-display \
                --verbose \
                --watch-serial \
                --no-test-xmhf

workflows:
  test-xmhf-workflow:
    jobs:
      - test-xmhf:
          matrix:
            parameters:
              subarch: ["i386", "amd64"]
