name: Build XMHF with TrustVisor

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_arch:
          - 'i386'
          - 'amd64'
        compile_mode:
          - 'debug'
          - 'release'
        optimize_mode:
          - 'O0'
          - 'O3'
        nested_virt:
          - 'nv'
          - 'no_nv'

    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: |
        sudo apt-get update && \
        sudo apt-get install \
                      openssh-server tmux vim git aptitude \
                      pbuilder texinfo ruby build-essential autoconf libtool \
                      crossbuild-essential-i386 gcc-mingw-w64 \
                      -y
    - name: Build
      run: |
        ./tools/ci/build.sh \
          ${{ matrix.target_arch }} \
          ${{ matrix.compile_mode }} \
          ${{ matrix.optimize_mode }} \
          ${{ matrix.nested_virt }}
    - name: Release
      uses: actions/upload-artifact@v2
      with:
        name: boot-${{ matrix.target_arch }}-${{ matrix.compile_mode }}-${{ matrix.optimize_mode }}-${{ matrix.nested_virt }}
        path: |
          xmhf/src/xmhf-core/xmhf-secureloader/sl_syms.exe
          xmhf/src/xmhf-core/xmhf-bootloader/init_syms.exe
          xmhf/src/xmhf-core/xmhf-runtime/runtime.exe
          hypervisor-x86-${{ matrix.target_arch }}.bin.gz
          init-x86-${{ matrix.target_arch }}.bin
    - name: Build pal_demo Linux
      if: ${{ matrix.compile_mode == 'debug' && matrix.optimize_mode == 'O0' && matrix.nested_virt == 'no_nv' }}
      run: |
        ./tools/ci/build_pal_demo.sh linux ${{ matrix.target_arch }}
    - name: Release pal_demo Linux
      if: ${{ matrix.compile_mode == 'debug' && matrix.optimize_mode == 'O0' && matrix.nested_virt == 'no_nv' }}
      uses: actions/upload-artifact@v2
      with:
        name: pal_demo-linux-${{ matrix.target_arch }}
        path: |
          hypapps/trustvisor/pal_demo/main
          hypapps/trustvisor/pal_demo/test
          hypapps/trustvisor/pal_demo/test_args
    - name: Build pal_demo Windows
      if: ${{ matrix.compile_mode == 'debug' && matrix.optimize_mode == 'O0' && matrix.nested_virt == 'no_nv' }}
      run: |
        ./tools/ci/build_pal_demo.sh windows ${{ matrix.target_arch }}
    - name: Release pal_demo Windows
      if: ${{ matrix.compile_mode == 'debug' && matrix.optimize_mode == 'O0' && matrix.nested_virt == 'no_nv' }}
      uses: actions/upload-artifact@v2
      with:
        name: pal_demo-windows-${{ matrix.target_arch }}
        path: |
          hypapps/trustvisor/pal_demo/main.exe
          hypapps/trustvisor/pal_demo/test.exe
          hypapps/trustvisor/pal_demo/test_args.exe

