name: Build XMHF with TrustVisor

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_arch:
          - 'x86'
          - 'x86_64'
        compile_mode:
          - 'debug'
          - 'release'

    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: |
        sudo apt-get update && \
        sudo apt-get install \
                      openssh-server tmux vim git aptitude \
                      pbuilder texinfo ruby build-essential autoconf libtool \
                      crossbuild-essential-i386 \
                      -y
    - name: Build
      run: |
        ./.github/build.sh \
          ${{ matrix.target_arch }} \
          ${{ matrix.compile_mode }}
    - name: Release
      uses: actions/upload-artifact@v2
      with:
        name: boot-${{ matrix.target_arch }}
        path: |
          xmhf/src/xmhf-core/xmhf-secureloader/sl_syms.exe
          xmhf/src/xmhf-core/xmhf-bootloader/init_syms.exe
          xmhf/src/xmhf-core/xmhf-runtime/runtime.exe
          hypervisor-${{ matrix.target_arch }}.bin.gz
          init-${{ matrix.target_arch }}.bin

